# Temporary sample generation notebook

In the future, the idea is have the samples to be generated daily, automatically and dynamically

for the pilot test, the sample is pregenerated

In [ ]:
import pandas as pd

In [13]:
# read the CSV into a DataFrame
df = pd.read_csv(
    './ai-popup-lab-backend/country_data/stratification_frames/sweden_strat_frame.csv'
)


df.head()

   MunicipalityCode MunicipalityName    Age     Sex        Education      N
0               114   Upplands Väsby  18-22  Female   Primary 9-10yr  944.2
1               114   Upplands Väsby  18-22  Female     Primary <9yr    6.8
2               114   Upplands Väsby  18-22  Female    Tertiary 2yr+   80.8
3               114   Upplands Väsby  18-22  Female    Tertiary <2yr  263.5
4               114   Upplands Väsby  18-22  Female  Upper secondary  927.7

In [14]:
# Sample 10,000 people from the dataframe, where each row can be sampled N times

df_sampled = df.loc[df.index.repeat(df['N'].astype(int))].sample(n=10000, random_state=42).reset_index(drop=True)

len(df_sampled)

10000

In [15]:
df_sampled = df_sampled.drop('N', axis = 1)
df_sampled = df_sampled.drop('MunicipalityCode', axis=1)
df_sampled.head()

  MunicipalityName    Age     Sex        Education
0        Stockholm  51-60  Female  Upper secondary
1           Nässjö  41-50  Female    Tertiary <2yr
2        Haparanda  51-60  Female  Upper secondary
3        Stockholm  61-70  Female  Upper secondary
4         Borlänge  18-22  Female  Upper secondary

In [17]:
df_sampled.reset_index().to_csv('sweden_daily_sample.csv', index=False)